#!/bin/bash
#
#    @(#)  [MB] cy_colorize Version 1.11 du 19/10/07 - 
#

colorize()
{
     type hl 2> /dev/null
     if [ $? = 0 ]; then
          hl -e                    			\
          -1B '^\[[A-Z_ ]*\]'      			\
          -2b '^ +-.+'             			\
          -3c ' +([^ ]+)'          			\
          -3R '^((\./)?a003:.+)'   			\
          -3y '^(MAIN) '           			\
          -1B 'STACK EMPTY'        			\
          -2c 'STACK'              			\
          -3c 'STACK *([0-9]+)'    			\
          -2g '\-?[0-9]+'          			\
		-1g '\<(NIL|INT|DOUBLE|STRING|LITTERAL|MATRIX|LIST|OPAIR|TUPLE|TEXT|LITTERAL|NEURAL MLP)\>'	\
          -2y 'STRING +\[(.*)\]'   			\
          -1B ': (BEGIN)\>'					\
		-2b '=+ #.*'						\
		-2B '\[([^]]*)\]'					\
		-3r '<[^>]*>'						\
		-3g 'Homogeneous'					\
		-3r 'Heterogeneous'					\
		-1b '\<UNUSED\>'					\
		-2g 'IPERF_LEX.*'					\
		-3g 'IPERF_YACC.*'					\
		-2B 'STRING +\[([a-zA-Z].*)\]'		\
		-3y 'STRING +\[(.*)\]'				\
		-3r '> LIST +\[(empty list)\]'		\
		-1B 'LIST +\[((Client|Server).+)\]'	\
		-1m '^Default .*'					\
		-3r '\<NOT FOUND'					\
		-3g '\<found\>'					\
		-1g '.* successfully added.*'			\
		-3Y 'dl_params_dyn_node_cmp\(\)'		\
		-3Y '\<func\>'						\
		-2M 'dl_search_matching_op\(.*\)'		\
		-3R '.* hide .*'					\
		-3R '\<UNDEFINED\>'					\
		-1R '^RPN>'						\
		--sep4
     else
          cat

          cat << EOF

          =====================================================================
          It seems that the "hl" command is not installed on your system,
          or your PATH variable is not properly configured.

          If the "hl" command is not installed, you should consider installing
          it from Github with the following command :
               git clone https://github.com/mbornet-hl/hl
               cd hl/src
               make
          then copy the "hl" command in a directory of your PATH variable.
          =====================================================================
EOF
     fi
}
