#!/bin/bash
#
#    @(#)  [MB]  Version 1.4 du 19/01/21 - 
#

gen_page()
{
     cat <<- EOF
          read_mnist

     EOF

     for j in  {1..10}
     do
          cat <<-EOF
               get
               label
               lastx
               mat
               x<>y
               mat7seg
               hcat
               hrev
               rdn
          EOF

          for i in {1..9}
          do
               cat <<- EOF
                    get
                    label
                    lastx
                    mat
                    x<>y
                    mat7seg
                    hcat
                    hrev
                    rup
                    x<>y
                    hcat
                    rdn

               EOF

          done
          if [ $j != 1 ]; then
               cat <<- EOF
                    rup
                    rup
                    stk
                    vcat
                    rdn
               EOF
          fi
     done

     cat <<- EOF
          rup
          stk
          'mnist_with_labels_page_01.txt'
          filename
          write
     EOF
}

gen_page | ./rpn > /dev/null

mv 'mnist_with_labels_page_01.txt' TEXTS/GROUPS
gnuplot -e 'RADIX="mnist_with_labels_page_01"' TOOLS/plot_digits_1920
