#!/bin/bash
#
#	Usage : ./rpn_test [--hl] RPN_test_file
#
#	@(#)	[MB] cy_rpn_test	Version 1.1 du 21/08/15 - 
#

. colorize


# Function run_RPN()
# ~~~~~~~~~~~~~~~~~~
run_RPN()
{
	# Commands for the RPN interpreter
	# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	sed '/^[ 	]*#/d' <<- EOF | ./rpn
		"toto" "titi" cat
	EOF
}

# Main program
# ~~~~~~~~~~~~
case "$1" in
	# Colorize output
	# ~~~~~~~~~~~~~~~
	"--hl")		run_RPN | colorize
				;;

	# Do not run RPN : colorize input only
	# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	"--only_hl")	colorize
				;;

	# Run RPN without colorization
	# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	*)			run_RPN
				;;
esac

