
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 37
#define YY_END_OF_BUFFER 38
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[407] =
    {   0,
        0,    0,   38,   34,   36,   34,   33,   34,   34,   22,
       34,   14,   14,   32,   10,   10,   10,   34,   34,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,    0,    0,   33,    0,   12,    0,
        3,    0,   13,   10,   10,   11,    0,   10,   10,    0,
        0,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   21,
       31,   31,   21,   31,   31,   31,   31,   31,   31,   31,
       21,   31,   22,   31,   14,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,    0,    0,
        0,   31,    1,    0,   11,   22,    0,    0,    0,    5,
       31,   31,   31,   31,    9,   15,   31,   17,   22,   31,
       31,   31,   31,   31,   31,   21,   31,   22,   31,   31,
       18,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   14,   31,   29,   24,   31,
        8,   31,   31,   31,   31,   31,   31,   17,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,

       22,   31,   31,   22,   31,   26,   31,   31,   31,   31,
        0,   31,    0,    0,    0,   31,   31,   31,   23,   31,
       31,   31,   17,   31,   15,   31,   31,   14,   31,   31,
       31,   22,   31,   31,   31,   31,   31,   31,   31,   31,
       18,   27,   31,   31,   31,   24,   31,   31,   31,   31,
       31,   31,   31,   31,   17,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   17,    2,   35,    0,   31,
       31,   31,   31,   31,   31,   31,   31,   28,   31,   31,
       31,   31,   31,   31,   31,   25,   31,   31,   31,   31,
       31,   31,   20,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   16,   19,   31,   27,   19,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   24,   31,   31,   31,   31,
        6,   31,   31,   31,   18,   31,   31,   31,   31,    0,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,    4,   31,   31,   30,   31,    7,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   25,   31,   31,   31,   31,   31,   31,   31,   27,
       31,   31,   25,   31,   31,   31,   31,   31,   31,   31,

       31,   31,   31,   31,   31,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    4,    1,    1,    1,
        1,    5,    1,    6,    7,    1,    8,    1,    9,    1,
        1,   10,   11,    1,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   19,   21,   20,   20,    1,    1,   22,
        1,   23,    1,    1,   24,   25,   26,   24,   27,   24,
       28,   24,   29,   24,   24,   24,   24,   30,   31,   32,
       32,   32,   32,   24,   24,   24,   24,   33,   24,   24,
       34,    1,    1,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
       61,   62,    1,    1,    1,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1
    } ;

static yyconst flex_int16_t yy_base[412] =
    {   0,
        0,    0,  580,  581,  581,   33,  574,  572,  574,  581,
      567,  581,   53,  581,  562,   62,   71,  547,  517,   54,
      511,   64,   62,   45,  526,   44,   60,   73,    0,   76,
       87,   88,   86,   97,  513,  106,  116,   93,  514,  119,
      514,  127,  532,  517,  533,  548,  558,  556,  581,  558,
      581,  551,  581,  546,  161,  168,  498,  177,  186,  529,
      499,    0,  504,  496,  512,  515,  506,  513,  493,  507,
      491,  491,  104,  490,  503,  495,   86,  116,  486,  479,
      163,  492,  160,  502,  497,  487,  484,  495,  493,  162,
      174,  159,    0,  176,  581,  477,   94,  483,  486,  482,

      493,  471,  490,  481,  468,  474,  166,  166,  468,  477,
      473,  470,  115,  467,  460,  480,  475,  459,  177,  460,
      466,  476,  461,  458,  468,  184,  471,  462,  483,  488,
      444,  466,  581,   45,  213,  581,  442,  472,  448,    0,
      462,  450,  447,  445,    0,  458,  438,    0,  449,  455,
      199,  439,  438,  189,  448,    0,  432,  203,  446,  450,
      449,  428,  425,  431,  430,  439,  425,  437,  421,  422,
      432,  433,  417,  432,  224,  220,  421,    0,    0,  415,
        0,  432,  416,  422,  423,  410,  421,  427,  426,  405,
      416,  403,  422,  417,  400,  414,  406,  395,  416,  402,

      406,  393,  397,  403,  398,    0,  149,  390,  404,  387,
      196,  386,  378,  410,  391,  377,  382,  388,    0,  379,
      386,  396,    0,  395,    0,  377,  375,    0,  379,  402,
      209,    0,  373,  372,  365,  382,  375,  362,  371,  364,
        0,    0,  404,  363,  367,  356,  359,  357,  365,  358,
      375,  369,  364,  361,  371,  346,  369,  353,  366,  194,
       69,  219,  361,  356,  359,  581,  581,  581,  358,  336,
      360,  345,  354,  386,  337,  351,  354,    0,  342,  348,
      345,  350,  331,  344,  328,    0,  339,  341,  336,  344,
      323,  337,    0,  332,  326,  334,  221,  320,  319,  335,

      323,  234,  325,  327,    0,    0,  317,  331,  581,  325,
      307,  321,  327,  323,  305,  311,  303,  321,  307,  311,
      314,  262,  311,  305,  300,  300,  300,  294,  288,  299,
      296,  304,  308,  282,  290,  581,  301,  290,  300,  297,
        0,  288,  292,  294,    0,  294,  282,  284,  291,  266,
      294,  284,  273,  287,  285,  269,  268,  278,  273,  280,
      284,    0,  264,  270,    0,  263,  270,  276,  276,  277,
      272,  258,  257,  255,  272,  254,  248,  248,  253,  263,
      258,  247,  243,  240,  243,  261,  241,  240,  254,    0,
      254,  256,    0,  251,  252,  236,  244,  245,  230,  229,

      230,  203,  204,  191,  136,  581,  275,  278,  281,   93,
      284
    } ;

static yyconst flex_int16_t yy_def[412] =
    {   0,
      406,    1,  406,  406,  406,  406,  406,  407,  408,  406,
      409,  406,  406,  406,  406,  406,  406,  406,  406,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  406,  406,  406,  407,  406,  408,
      406,  409,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  406,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  406,  406,
      406,  410,  406,  406,  406,  406,  406,  406,  406,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      406,  410,  406,  406,  406,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  406,  406,  406,  406,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  406,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  406,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  411,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  411,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,    0,  406,  406,  406,  406,
      406
    } ;

static yyconst flex_int16_t yy_nxt[645] =
    {   0,
        4,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   13,   14,   12,   15,   16,   17,   17,   17,   17,
       17,    4,    4,    4,   18,    4,    4,    4,    4,    4,
        4,    4,   19,    4,   12,    4,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,    4,   45,  213,  213,   46,   54,   55,   55,
       55,   55,   55,   55,   56,   57,   58,   59,   59,   59,
       59,   59,   59,   56,   83,   59,   59,   59,   59,   59,
       59,   59,   63,   64,   79,   62,   95,   80,   84,   80,

       71,   65,   76,   66,   81,  302,   77,   72,   67,   68,
       69,   73,   90,   85,   74,   86,   91,   75,   78,  303,
       92,   87,   88,   96,   89,   93,   94,   97,   80,  123,
      177,   80,  100,  105,   93,   98,   99,  103,  101,  104,
      152,  106,  178,  102,  111,  112,  113,  107,  129,  124,
      108,  194,  115,  109,  116,  117,  118,   84,  147,  126,
      119,  130,  114,  148,  153,  228,  228,  154,  120,  195,
      127,  121,   85,   56,  122,   59,   59,   59,   59,   59,
       59,   59,  135,  135,  135,  135,  135,  135,  135,   56,
      286,   59,   59,   59,   59,   59,   59,   59,   56,  168,

       59,   59,   59,   59,   59,   59,   59,  157,  172,  160,
      170,  137,  174,  173,  158,  161,  169,  188,  175,  200,
      190,  156,  207,  171,  189,  148,  201,  135,  135,  135,
      135,  135,  135,  135,  221,  156,  225,  208,  227,  243,
      244,  300,  301,  266,  336,  336,  405,  404,  148,  279,
      228,  266,  280,  281,  222,  245,  266,  266,  223,  227,
      304,  330,   93,  350,  282,  283,  350,  350,  305,  331,
      350,  406,  403,  402,  406,   48,   48,   48,   50,   50,
       50,   52,   52,   52,  367,  148,  367,   93,  401,  400,
      399,  242,  398,  345,  397,  396,  286,  395,  148,  206,

      394,  393,  392,  391,  286,  390,  389,  361,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  286,  373,  372,  371,  370,  369,  368,
      345,  241,  366,  241,  365,  206,  364,  242,  363,  362,
      219,  361,  360,  359,  242,  358,  357,  356,  355,  354,
      353,  352,  351,  286,  349,  348,  347,  346,  345,  344,
      179,  343,  342,  341,  340,  286,  339,  338,  305,  337,
      335,  334,  333,  332,  329,  328,  327,  306,  326,  325,
      324,  323,  225,  322,  206,  321,  320,  319,  318,  317,
      316,  315,  314,  136,  313,  312,  311,  310,  309,  308,

      307,  306,  299,  298,  297,  148,  296,  148,  295,  178,
      294,  293,  292,  291,  290,  179,  289,  288,   93,  287,
      286,  148,  206,  178,  206,  285,  284,  278,  277,  276,
      148,  275,  274,  223,  273,  272,  271,  270,  269,  268,
      267,   93,  265,   93,  264,  263,  219,  262,   93,  219,
      261,  260,  179,  259,  242,  258,  257,  256,  145,  255,
      254,  227,  253,  178,  252,  251,  250,  249,  248,  247,
      246,  242,  241,  189,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  232,  231,  230,  229,  145,  226,  148,
      224,  220,  219,  148,  218,  217,  201,  216,  199,  215,

      214,  136,  212,  136,  136,  211,  210,  209,  206,  205,
      204,  203,  148,  202,  199,  198,  197,  196,  148,  148,
      193,  192,  191,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  176,  167,  166,  165,  164,  163,  162,  159,
      156,  155,  151,  150,  149,   93,  146,  145,  144,  123,
      143,  142,  141,  140,   74,  139,  138,  136,   56,   53,
       51,   49,   47,  134,  133,  132,  131,  128,  125,  110,
       82,   70,   61,   60,   56,   53,   51,   49,   47,  406,
        3,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406
    } ;

static yyconst flex_int16_t yy_chk[645] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    6,  134,  134,    6,   13,   13,   13,
       13,   13,   13,   13,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   17,   26,   17,   17,   17,   17,   17,
       17,   17,   20,   20,   24,  410,   31,   24,   27,   26,

       22,   20,   23,   20,   24,  261,   23,   22,   20,   20,
       20,   22,   30,   27,   22,   28,   30,   22,   23,  261,
       30,   28,   28,   31,   28,   30,   30,   31,   32,   38,
       97,   30,   32,   34,   77,   31,   31,   33,   32,   33,
       77,   34,   97,   32,   36,   36,   36,   34,   42,   38,
       34,  113,   37,   34,   37,   37,   37,   40,   73,   40,
       37,   42,   36,   73,   78,  207,  207,   78,   37,  113,
       40,   37,   40,   55,   37,   55,   55,   55,   55,   55,
       55,   55,   56,   56,   56,   56,   56,   56,   56,   58,
      405,   58,   58,   58,   58,   58,   58,   58,   59,   90,

       59,   59,   59,   59,   59,   59,   59,   81,   92,   83,
       91,   58,   94,   92,   81,   83,   90,  107,   94,  119,
      108,   83,  126,   91,  107,  108,  119,  135,  135,  135,
      135,  135,  135,  135,  151,   91,  154,  126,  158,  175,
      176,  260,  260,  211,  302,  302,  404,  403,  154,  231,
      158,  211,  231,  231,  151,  176,  211,  211,  151,  175,
      262,  297,  402,  322,  231,  231,  322,  350,  262,  297,
      350,  367,  401,  400,  367,  407,  407,  407,  408,  408,
      408,  409,  409,  409,  411,  399,  411,  398,  397,  396,
      395,  394,  392,  391,  389,  388,  387,  386,  385,  384,

      383,  382,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  366,  364,  363,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      349,  348,  347,  346,  344,  343,  342,  340,  339,  338,
      337,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  308,  307,  304,  303,
      301,  300,  299,  298,  296,  295,  294,  292,  291,  290,
      289,  288,  287,  285,  284,  283,  282,  281,  280,  279,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  265,

      264,  263,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  240,
      239,  238,  237,  236,  235,  234,  233,  230,  229,  227,
      226,  224,  222,  221,  220,  218,  217,  216,  215,  214,
      213,  212,  210,  209,  208,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  180,
      177,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      165,  164,  163,  162,  161,  160,  159,  157,  155,  153,
      152,  150,  149,  147,  146,  144,  143,  142,  141,  139,

      138,  137,  132,  131,  130,  129,  128,  127,  125,  124,
      123,  122,  121,  120,  118,  117,  116,  115,  114,  112,
      111,  110,  109,  106,  105,  104,  103,  102,  101,  100,
       99,   98,   96,   89,   88,   87,   86,   85,   84,   82,
       80,   79,   76,   75,   74,   72,   71,   70,   69,   68,
       67,   66,   65,   64,   63,   61,   60,   57,   54,   52,
       50,   48,   47,   46,   45,   44,   43,   41,   39,   35,
       25,   21,   19,   18,   15,   11,    9,    8,    7,    3,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cy_rpn_lex.l"
#line 2 "cy_rpn_lex.l"
/*
 * Copyright (C) 2017-2019, Martial Bornet
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *   @(#)  [MB] cy_rpn_lex.l Version 1.69 du 19/10/19 - 
 */

#include  "cy_rpn_header.h"
#include  "cy_rpn_proto.h"
#include  "../ci/ci_epub.h"

extern struct rpn_operator      rpn_operators[];

#line 764 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 72 "cy_rpn_lex.l"


#line 954 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 407 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 581 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 74 "cy_rpn_lex.l"
{
                    int                      _num;

                    _num                     = yytext[2] - 'P' + 1;

                    /* TODO : For future use
                       ~~~~~~~~~~~~~~~~~~~~~ */
                    RPN_TRACE_LEX("FUNCT KEY%02d\n", _num);
               }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 84 "cy_rpn_lex.l"
{
                    int                      _c, _num;

                    _c                       = yytext[3] - '0';

                    switch (_c) {
                         case 5 :
                              _num                = 5;
                              break;

                         case 7 :
                              _num                = 6;
                              break;

                         case 8 :
                              _num                = 7;
                              break;

                         case 9 :
                              _num                = 8;
                              break;

                         default:
                              _num                = 0;
                              break;
                    }

                    /* TODO : For future use
                       ~~~~~~~~~~~~~~~~~~~~~ */
                    RPN_TRACE_LEX("FUNCT KEY%02d\n", _num);
               }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 116 "cy_rpn_lex.l"
{
                    RPN_TRACE_LEX("========== %s ==========\n", yytext);
               }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 120 "cy_rpn_lex.l"
{
                    fprintf(stderr, "RPN Version %s\n", G.version);
               }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 124 "cy_rpn_lex.l"
{
                    // TODO : A TRAITER CORRECTEMENT => creer operateur
                    printf("\n");
               }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 129 "cy_rpn_lex.l"
{
                    rpn_catalog(rpn_operators);
               }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 133 "cy_rpn_lex.l"
{
                    char                *_p;

                    RPN_TRACE_LEX("yytext = [%s]\n", yytext);

                    /* Search for space or tab (skip "import" keyword)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    for (_p = yytext; *_p != ' ' && *_p != '\t'; _p++);

                    /* Skip spaces and tabs (search for module name)
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    for ( ; *_p == ' ' || *_p == '\t'; _p++);

                    /* Import module
                       ~~~~~~~~~~~~~ */
                    G.err_no			= rpn_import(strdup(_p));
               }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 151 "cy_rpn_lex.l"
{
                    rpn_elt                  *_elt_nil;

                    /* Allocate element descriptors
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    _elt_nil            = rpn_new_elt(RPN_TYPE_NIL);

                    /* Push element on the stack
                       ~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    G.stack->new_value  = TRUE;
                    rpn_push(G.stack, _elt_nil);
               }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 164 "cy_rpn_lex.l"
{
				yyterminate();
			}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 168 "cy_rpn_lex.l"
{
                    rpn_elt                  *_elt_i;

                    /* Allocate element descriptors
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    _elt_i              = rpn_new_elt(RPN_TYPE_INT);
                    _elt_i->value.i     = atoi(yytext);

                    /* Push element on the stack
                       ~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    G.stack->new_value  = TRUE;
                    rpn_push(G.stack, _elt_i);
               }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 182 "cy_rpn_lex.l"
{
                    rpn_elt                  *_elt_f;

                    /* Allocate element descriptors
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    _elt_f              = rpn_new_elt(RPN_TYPE_DOUBLE);
                    _elt_f->value.d     = atof(yytext);

                    /* Push element on the stack
                       ~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    G.stack->new_value  = TRUE;
                    rpn_push(G.stack, _elt_f);
               }
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 196 "cy_rpn_lex.l"
{
                    rpn_elt                  *_elt_s;

                    /* Allocate element descriptors
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    _elt_s              = rpn_new_elt(RPN_TYPE_STRING);
                    _elt_s->value.s     = strdup(yytext);

                    if (rpn_strip_quotes(&_elt_s->value.s) != RPN_RET_OK) {
                         rpn_err_msg_invalid_string(_elt_s->value.s);
                    }
                    else {
                         /* Push element on the stack
                            ~~~~~~~~~~~~~~~~~~~~~~~~~ */
                         G.stack->new_value  = TRUE;
                         rpn_push(G.stack, _elt_s);
                    }
               }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 215 "cy_rpn_lex.l"
{
                    rpn_elt                  *_elt_s;
				rpn_litteral			*_litteral;

                    /* Allocate element descriptors
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
				_litteral				= rpn_new_litteral();
				_litteral->value		= strdup(yytext);

                    _elt_s				= rpn_new_elt(RPN_TYPE_LITTERAL);
				_elt_s->value.obj		= _litteral;

                    if (rpn_strip_single_quotes(&_litteral->value) != RPN_RET_OK) {
                         rpn_err_msg_invalid_string(_litteral->value);
                    }
                    else {
                         /* Push element on the stack
                            ~~~~~~~~~~~~~~~~~~~~~~~~~ */
                         G.stack->new_value  = TRUE;
                         rpn_push(G.stack, _elt_s);
                    }
               }
	YY_BREAK
case 14:
#line 239 "cy_rpn_lex.l"
case 15:
#line 240 "cy_rpn_lex.l"
case 16:
#line 241 "cy_rpn_lex.l"
case 17:
#line 242 "cy_rpn_lex.l"
case 18:
#line 243 "cy_rpn_lex.l"
case 19:
#line 244 "cy_rpn_lex.l"
case 20:
#line 245 "cy_rpn_lex.l"
case 21:
#line 246 "cy_rpn_lex.l"
case 22:
#line 247 "cy_rpn_lex.l"
case 23:
#line 248 "cy_rpn_lex.l"
case 24:
#line 249 "cy_rpn_lex.l"
case 25:
#line 250 "cy_rpn_lex.l"
case 26:
#line 251 "cy_rpn_lex.l"
case 27:
#line 252 "cy_rpn_lex.l"
case 28:
#line 253 "cy_rpn_lex.l"
case 29:
#line 254 "cy_rpn_lex.l"
case 30:
#line 255 "cy_rpn_lex.l"
case 31:
YY_RULE_SETUP
#line 255 "cy_rpn_lex.l"
{
                    char                     *_op_name;
                    dl_operator              *_op;
                    int                       _retcode;

				RPN_TRACE_LEX("Searching for operator [%s]\n", strdup(yytext));

                    /* Initialize operator name
                       ~~~~~~~~~~~~~~~~~~~~~~~~ */
                    _op_name				= strdup(yytext);

                    RPN_TRACE_LEX("operator = [%s]\n", _op_name);

                    if ((_op = rpn_search_op(G.stack, _op_name)) != 0) {
                         /* Execute operator
                            ~~~~~~~~~~~~~~~~ */
                         if ((_retcode = rpn_op(G.stack, _op)) != RPN_RET_OK) {
                              rpn_err_msg_op_error(_op->op_name, _retcode);
                         }
                    }
               }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 277 "cy_rpn_lex.l"
{
                    char                     *_op_name;
                    int                       _retcode;

                    /* Initialize operator name
                       ~~~~~~~~~~~~~~~~~~~~~~~~ */
                    _op_name				= strdup(yytext);

                    RPN_TRACE_LEX("operator = [%s]\n", _op_name);

                    if (G.stack->last_op) {
                         /* Execute previous operator
                            ~~~~~~~~~~~~~~~~~~~~~~~~~ */
                         if ((_retcode = rpn_op(G.stack, G.stack->last_op)) != RPN_RET_OK) {
                              rpn_err_msg_op_error(G.stack->last_op->op_name, _retcode);
                         }
                    }
               }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 296 "cy_rpn_lex.l"
;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 298 "cy_rpn_lex.l"
{
                    printf("[%s] ", yytext);
               }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 302 "cy_rpn_lex.l"
{
                    rpn_inc_begin(G.stack);
                    rpn_elt                  *_elt;

                    /* Allocate element descriptors
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    _elt                = rpn_new_elt(RPN_TYPE_START_MARKER);

                    /* Push element on the stack
                       ~~~~~~~~~~~~~~~~~~~~~~~~~ */
                    G.stack->new_value  = TRUE;
                    rpn_push(G.stack, _elt);
               }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 316 "cy_rpn_lex.l"
{
				rpn_disp_prompt();
               }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 320 "cy_rpn_lex.l"
{
				yyterminate();
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 324 "cy_rpn_lex.l"
ECHO;
	YY_BREAK
#line 1372 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 407 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 407 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 406);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 324 "cy_rpn_lex.l"



/******************************************************************************

                              MAIN

******************************************************************************/
int main(int argc, char *argv[])
{
	char				*_optstrg = "CdhlnsvyLY";
	int				 _opt, _no_rc = FALSE;
	char				*_rc_file = ".rpn.rc";
	FILE				*_fp_rc;

     G.progname          = argv[0];
     G.prompt            = "RPN> ";
     G.version           = RPN_VERSION;

	while ((_opt = getopt(argc, argv, _optstrg)) != -1) {
		switch (_opt) {

		case	'C':
			G.debug_level		|= RPN_DBG_DISP_CMDS;
			break;

		case	'd':
			G.debug_level		|= RPN_DBG_DEBUG;
			break;

		case	'h':
			cy_usage(_optstrg);
			break;

		case	'l':
			G.debug_level		|= RPN_DBG_LEX;
			break;

		case	'n':
			_no_rc			= TRUE;
			break;

		case 's':
			G.silent			= TRUE;
			break;

		case	'v':
			G.debug_level		|= RPN_DBG_VERBOSE;
			break;

		case	'y':
			G.debug_level		|= RPN_DBG_YACC;
			break;

		case	'L':
			G.debug_level		|= RPN_DBG_LEX_2;
			break;

		case	'Y':
			G.debug_level		|= RPN_DBG_YACC_2;
			break;

		default:
			fprintf(stderr, "Usage: %s [-%s]\n", G.progname, _optstrg);
			exit(RPN_EXIT_USAGE);
		}
	}

     /* Allocate stack descriptor
        ~~~~~~~~~~~~~~~~~~~~~~~~~ */
     G.stack             = rpn_new_stack("MAIN");
     G.sigma             = rpn_new_sigma("default");

     /* Initialize the root of the modules tree
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
     ci_init_root(&G.modules_tree);

     /* Initialize the handling of the SIGSEGV signal
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
     rpn_init_backtrace();

#if 0
	if (!G.silent) {
		/* Display stack
		   ~~~~~~~~~~~~~ */
		rpn_disp_stack(G.stack);
	}
#endif

	rpn_disp_prompt();

	if (!_no_rc) {
		/* Search for a readable commands file (.rpn.rc)
		   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
		if (access(_rc_file, 0) == 0) {
			if ((_fp_rc = fopen(_rc_file, "r")) == 0) {
				fprintf(stderr, "%s: cannot open \"%s\" !\n", G.progname, _rc_file);
			}
			else {
				yyrestart(_fp_rc);
				yylex();
			}
		}
	}

	if (G.silent) {
		/* Reset debug level
		   ~~~~~~~~~~~~~~~~~ */
		G.debug_level = 0;
	}

	yyrestart(stdin);
     yylex();

     rpn_free_stack(G.stack);

     return 0;
}

/******************************************************************************

                              REMOVE_WARN_UNUSED

******************************************************************************/
static void remove_warn_unused(int always_false)
{
     if (always_false == TRUE) {
          yyunput(0, 0);
          input();
     }
}

/******************************************************************************

                              YYERROR

******************************************************************************/
void yyerror(char *errmsg)
{
     fprintf(stderr, "%s: Parser error: %s\n", G.progname, errmsg);
     remove_warn_unused(FALSE);
     exit(RPN_EXIT_SYNTAX);
}

/******************************************************************************

                              YYWRAP

******************************************************************************/
int yywrap()
{
     return 1;
}

/******************************************************************************

						CY_USAGE

******************************************************************************/
void cy_usage(char *optstrg)
{
	fprintf(stderr, "Usage: %s [-%s]\n", G.progname, optstrg);
	fprintf(stderr, "  -C : display commands\n");
	fprintf(stderr, "  -d : activate debug\n");
	fprintf(stderr, "  -h : help\n");
	fprintf(stderr, "  -l : display lex debug (parser 1)\n");
	fprintf(stderr, "  -n : do not read the rc file\n");
	fprintf(stderr, "  -s : silent\n");
	fprintf(stderr, "  -v : verbose\n");
	fprintf(stderr, "  -y : display yacc debug (parser 1)\n");
	fprintf(stderr, "  -L : display lex debug (parser 2)\n");
	fprintf(stderr, "  -Y : display yacc debug (parser 2)\n");
	exit(RPN_EXIT_USAGE);
}

