#!/bin/bash
#
#	@(#)	[MB] cy_test_litteral	Version 1.1 du 17/11/05 - 
#

(
	sed '/^#/d' <<- EOF | ./a005
		'a' 'b' +
		'c' 'd' -
		*
	EOF
) 2>&1 | hl -e				\
	-3R '^((\./)?a003:.+)'	\
	-1B 'STACK EMPTY'		\
	-2c 'STACK'			\
	-3c 'STACK *([0-9]+)'	\
	-2g '\-?[0-9]+'		\
	-1m '\<(INT|FLOAT|STRING|LITTERAL|MATRIX)\>'	\
	-2y 'STRING +\[(.*)\]'
