#!/bin/bash
#
#	@(#)	[MB] cy_test_mat_litteral	Version 1.1 du 17/11/05 - 
#

(
	sed '/^#/d' <<- EOF | ./a005
		'a11' 'a12' 'a13'
		'a21' 'a22' 'a23'
		'a31' 'a32' 'a33'
		3 3 mat

		'b11' 'b12' 'b13'
		'b21' 'b22' 'b23'
		'b31' 'b32' 'b33'
		3 3 mat
		*
	EOF
) 2>&1 | hl -e				\
	-3R '^((\./)?a003:.+)'	\
	-1B 'STACK EMPTY'		\
	-2c 'STACK'			\
	-3c 'STACK *([0-9]+)'	\
	-2g '\-?[0-9]+'		\
	-1m '\<(INT|FLOAT|STRING|LITTERAL|MATRIX)\>'	\
	-2y 'STRING +\[(.*)\]'
