#!/bin/bash
#
#	@(#)	[MB] cy_test_mat_float	Version 1.1 du 17/11/05 - 
#

(
	cat <<- EOF | ./a005
		1. 2. 3.
		4. 5. 6.
		7. 8. 9.
		3 3 mat

		3. 2. 1.
		6. 5. 4.
		9. 8. 7.
		3 3 mat

		*
	EOF
) 2>&1 | hl -e				\
	-3R '^((\./)?a003:.+)'	\
	-1B 'STACK EMPTY'		\
	-2c 'STACK'			\
	-3c 'STACK *([0-9]+)'	\
	-2g '\-?[0-9]+'		\
	-1m '\<(INT|FLOAT|STRING|LITTERAL|MATRIX)\>'	\
	-2y 'STRING +\[(.*)\]'
