#!/bin/bash
#
#	@(#)	[MB] cy_test_vec_float	Version 1.1 du 17/11/05 - 
#

(
	cat <<- EOF | ./a005
		1. 2. 3.
		1 3 mat

		10. 100. 1000.
		3 1 mat
		*

		1. 2. 3.
		3 1 mat

		10. 100. 1000.
		1 3 mat
		*
	EOF
) 2>&1 | hl -e				\
	-3R '^((\./)?a003:.+)'	\
	-1B 'STACK EMPTY'		\
	-2c 'STACK'			\
	-3c 'STACK *([0-9]+)'	\
	-2g '\-?[0-9]+'		\
	-1m '\<(INT|FLOAT|STRING|MATRIX)\>'	\
	-2y 'STRING +\[(.*)\]'
