#!/bin/bash
#
#	@(#)	[MB] cy_test_mat_3x3	Version 1.2 du 17/11/15 - 
#

. colorize

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		1 2 3
		4 5 6
		7 8 9
		3 3 mat

		10 20 30
		40 50 60
		70 80 90
		3 3 mat
		*

		1 2 3
		4 5 6
		7 8 9
		3 3 mat

		1 2 3
		4 5 6
		7 8 9
		3 3 mat
		*

		 8  9 10
		11 12 13
		14 15 16
		3 3 mat

		16 15 14
		13 12 11
		10  9  8
		3 3 mat
		*
		*
	EOF
) 2>&1 | colorize
