#!/bin/bash
#
#	@(#)	[MB] cy_test_rdn_rup	Version 1.1 du 17/11/15 - 
#

. colorize

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		1 2 3 1 3
		4 5 6 3 1 mat
		rdn
		mat
		rup
		*

		1 2 3 3 1
		4 5 6 1 3 mat
		rdn
		mat
		rup
		*
	EOF
) 2>&1 | colorize
