#!/bin/bash
#
#	@(#)	[MB] cy_test_vec_int	Version 1.2 du 17/11/15 - 
#

. colorize

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		1 2 3
		1 3 mat
		
		10 100 1000
		3 1 mat
		*

		1 2 3
		3 1 mat

		10 100 1000
		1 3 mat
		*
	EOF
) 2>&1 | colorize
