#!/bin/bash
#
#	@(#)	[MB] cy_test_mat_2x2	Version 1.2 du 17/11/15 - 
#

. colorize

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	sed '/^#/d' <<- EOF | "$RPN"
		2 3
		4 5
		2 2 mat

		10 20
		30 40
		2 2 mat
		*
	EOF
) 2>&1 | colorize
