#!/bin/bash
#
#	@(#)	[MB] cy_test_mat_4x4	Version 1.2 du 17/11/15 - 
#

. colorize

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		 1  2  3  4
		 5  6  7  8
		 9 10 11 12
		13 14 15 16
		4 4 mat

		16 15 14 13
		12 11 10  9
		 8  7  6  5
		 4  3  2  1
		4 4 mat

		*
	EOF
) 2>&1 | colorize
