#!/bin/bash
#
#	@(#)	[MB] cy_test_mat_id	Version 1.2 du 17/11/15 - 
#

. colorize

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		1 2 3
		4 5 6
		7 8 9
		3 3 mat

		1 0 0
		0 1 0
		0 0 1
		3 3 mat
		*
	EOF
) 2>&1 | colorize
