#!/bin/bash
#
#	@(#)	[MB] cy_test_mat_float	Version 1.2 du 17/11/15 - 
#

. colorize

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		1. 2. 3.
		4. 5. 6.
		7. 8. 9.
		3 3 mat

		3. 2. 1.
		6. 5. 4.
		9. 8. 7.
		3 3 mat

		*
	EOF
) 2>&1 | colorize
