#!/bin/bash
#
#	@(#)	[MB] cy_test_cross_product	Version 1.1 du 17/11/15 - 
#

. colorize

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		'a1' 'a2' 'a3' vec3
		'b1' 'b2' 'b3' vec3
		^
	EOF
) 2>&1 | colorize
