#!/bin/bash
#
#	%Z%	[%Y%] %M%	Version %I% du %E% - %Q%
#

(
	echo '"=" 12 3 * 4 + 2 * * length 10 / 2 / 2 / 2 /' | ./a004
	echo '"=" 2 4 12 3 * + * * length 10 / 2 / 2 / 2 /' | ./a004
	cat <<- EOF | ./a004
		"L'operateur " "+ " "a " "ete " "surcharge" "." + + + + + 
	EOF
) 2>&1 | hl -e				\
	-3R '^((\./)?a003:.+)'	\
	-1B 'STACK EMPTY'		\
	-2c 'STACK'			\
	-3c 'STACK *([0-9]+)'	\
	-2g '\-?[0-9]+'		\
	-1m '\<(INT|STRING)\>'	\
	-2y 'STRING +\[(.*)\]'
