-----   Dimanche 13 Octobre   2019  23:38:29
-----   Fichier var : rpn.var
-----   Fichier mis : rpn.mis
-----   Fichier v   : rpn.v
-----   Reference   : /home/machine/src/SCCS/MB

-----   make -f df_makefile -i VFILE=rpn.v LIB=lib
        MIS=/home/machine/src/SCCS/MB MAKE=/usr/bin/make AR=/usr/bin/ar
        LINT=/bin/lint LIB=lib RANLIB=/usr/bin/ranlib TEE=/usr/bin/tee CC=gcc
        CFLAGS=-Wall -Werror -Wuninitialized BE_C=-Wall -Werror -Wuninitialized
make[1]: Entering directory `/home/krypton/mb/GLMF/src/rpn_main/df'
ar: creating lib
a - df_convert.o
make[1]: Leaving directory `/home/krypton/mb/GLMF/src/rpn_main/df'
-----   ranlib lib 
-----   Creation d'objets terminee.
-----   Dimanche 13 Octobre   2019  23:38:29
