#!/bin/bash
#
#	%Z%	[%Y%] %M%	Version %I% du %E% - %Q%
#

colorize()
{
	type hl 2> /dev/null
	if [ $? = 0 ]; then
		hl -e				\
		-3R '^((\./)?a003:.+)'	\
		-1B 'STACK EMPTY'		\
		-2c 'STACK'			\
		-3c 'STACK *([0-9]+)'	\
		-2g '\-?[0-9]+'		\
		-1m '\<(INT|FLOAT|STRING|LITTERAL|MATRIX)\>'	\
		-2y 'STRING +\[(.*)\]'
	else
		cat
	fi
}
