#!/bin/bash
#
#	%Z%	[%Y%] %M%	Version %I% du %E% - %Q%
#

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	sed '/^#/d' <<- EOF | "$RPN"
		1 1 1 1
		0 1 1 1
		0 0 1 1
		0 0 0 1
		4 4 mat

		enter
		enter
		enter
		enter
		enter
		enter
		enter
		enter
		enter
		enter
		enter
		enter
		enter
		enter
		enter
		4 4 mat

		enter
		expl
		*
	EOF
) 2>&1 | hl -e				\
	-3R '^((\./)?a003:.+)'	\
	-1B 'STACK EMPTY'		\
	-2c 'STACK'			\
	-3c 'STACK *([0-9]+)'	\
	-2g '\-?[0-9]+'		\
	-1m '\<(INT|FLOAT|STRING|LITTERAL|MATRIX)\>'	\
	-2y 'STRING +\[(.*)\]'
#
