#!/bin/bash
#
#	%Z%	[%Y%] %M%	Version %I% du %E% - %Q%
#

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		1 2 3
		4 5 6
		7 8 9
		3 3 mat

		1 0 0
		0 1 0
		0 0 1
		3 3 mat
		*
	EOF
) 2>&1 | hl -e				\
	-3R '^((\./)?a003:.+)'	\
	-1B 'STACK EMPTY'		\
	-2c 'STACK'			\
	-3c 'STACK *([0-9]+)'	\
	-2g '\-?[0-9]+'		\
	-1m '\<(INT|FLOAT|STRING|MATRIX)\>'	\
	-2y 'STRING +\[(.*)\]'
