#!/bin/bash
#
#	%Z%	[%Y%] %M%	Version %I% du %E% - %Q%
#

if [ "$RPN" = "" ]; then
	RPN="./rpn"
fi

(
	cat <<- EOF | "$RPN"
		 1  2  3  4
		 5  6  7  8
		 9 10 11 12
		13 14 15 16
		4 4 mat

		16 15 14 13
		12 11 10  9
		 8  7  6  5
		 4  3  2  1
		4 4 mat

		*
	EOF
) 2>&1 | hl -e				\
	-3R '^((\./)?a003:.+)'	\
	-1B 'STACK EMPTY'		\
	-2c 'STACK'			\
	-3c 'STACK *([0-9]+)'	\
	-2g '\-?[0-9]+'		\
	-1m '\<(INT|FLOAT|STRING|LITTERAL|MATRIX)\>'	\
	-2y 'STRING +\[(.*)\]'
