#!/bin/bash
#
#	Show differences between two hosts files
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] ej_diff_hosts	Version 1.9 du 22/09/17 - 
#

TMP_HOSTS="/tmp/diff_hosts.$$"
TMP_DISP_MODE="/tmp/disp_mode.$$"

usage()
{
	cat <<- EOF
		Usage: $PROGNAME [-hHA] hosts_file hosts_file [hosts_file ...]
		  -h : help (display usage)
		  -H : display all hosts
		  -A : display all aliases

		  Environment variable : RPN         = "$RPN"
		  Environment variable : RPN_LIBPATH = "$RPN_LIBPATH"
	EOF
}

PROGNAME="$(basename "$0")"

if [ "$RPN" = '' ]; then
	RPN='rpn'
fi

while getopts "hHA" opt
do
	case	"$opt" in
		H)		echo "1 disp_all_hosts"   >> "$TMP_DISP_MODE"
				;;

		A)		echo "1 disp_all_aliases" >> "$TMP_DISP_MODE"
				;;

		h)		usage
				exit 1
				;;

		*)		usage
				exit 1
				;;
	esac
done
shift $((OPTIND-1))

if [ "$2" = '' ]; then
	usage
	exit 1
fi


if [ "$3" = '' ]; then
	# 2 hosts files
	# ~~~~~~~~~~~~~
	hosts1="$1"
	hosts2="$2"

	cat <<- EOF > "$TMP_HOSTS"
		"$hosts1" filename hostsfile
		"$hosts2" filename hostsfile
	EOF
else
	# More than 2 hosts files
	# ~~~~~~~~~~~~~~~~~~~~~~~
	(
		echo "BEGIN"
		for hosts in "$@"
		do
			echo '"'"$hosts"'" filename hostsfile'
		done
		echo "list"
	) > "$TMP_HOSTS"
fi

# Run RPN diff for hosts files
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cat <<- EOF | "$RPN" -ns
	import hosts
	import core
	$(cat "$TMP_DISP_MODE")
	$(cat "$TMP_HOSTS")
	diff
EOF

rm -f "$TMP_HOSTS" "$TMP_DISP_MODE"
