#!/bin/bash
#
#	Show differences between two hosts files
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] ej_diff_hosts	Version 1.1 du 21/10/20 - 
#

_hl()
{
     hl -e                                   \
     -3g '^ +([^ ]+) +\| +(\1)'              \
     -2B '^([0-9]{1,3}(\.[0-9]{1,3}){3})'    \
     -3r '^ +([^ ]+) +\| *$'                 \
     -3r '^ +\| *([^ ]+)$'
}

hosts1="$1"
hosts2="$2"

cat <<- EOF | ./rpn -ns | _hl
     import hosts
     import core
     "$hosts1" filename hostsfile
     "$hosts2" filename hostsfile
     diff
EOF
