#!/bin/bash
#
#	rpn_tool : do various operations related to rpn
#	~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
#	@(#)	[MB] eo_rpn_tool	Version 1.9 du 21/11/19 - 
#

# _hl {{{
_hl()
{
	if [ "$no_color" != 'true' ]; then
		hl "$@"
	else
		cat
	fi
}
# _hl }}}
# usage {{{
usage()
{
	# Is the "hl_tool" config available ?
	# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	hl -op hl_tool | grep -q '\<hl_tool\>'
	if [ $? = 0 ]; then
		# Yes : colorize the usage output
		# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		FILTER='hl --hl_tool'
	else
		# No : don't colorize
		# ~~~~~~~~~~~~~~~~~~~
		FILTER='cat'
	fi

	cat <<- EOF | $FILTER
		Usage: $PROGNAME [-N] [-h|-C|-c|-M|-s] [args]
		Version 1.9

		  -h : help (this message)
		  -N : no color

		  -C : display the catalog of operators for all modules
		       $(usage_catalog_all)

		  -c : display the catalog of operators for the specified module
		       $(usage_catalog)

		  -s : search modules containing specified operator
		       $(usage_search_op)

		  -M : list available modules
		       $(usage_list_modules)

	EOF
}
# usage }}}
# usage_catalog_all {{{

usage_catalog_all()
{
	cat <<- EOF
		Usage: $PROGNAME -C
	EOF
}

# usage_catalog_all }}}
# usage_catalog {{{

usage_catalog()
{
	cat <<- EOF
		Usage: $PROGNAME -c rpn_module
	EOF
}

# usage_catalog }}}
# usage_list_modules {{{

usage_list_modules()
{
	cat <<- EOF
		Usage: $PROGNAME -M
	EOF
}

# usage_list_modules }}}
# usage_search_op {{{

usage_search_op()
{
	cat <<- EOF
		Usage: $PROGNAME -s operator
	EOF
}

# usage_search_op }}}
# catalog_all {{{

catalog_all()
{
	if [ "$1" != '' ]; then
		usage_catalog_all
		exit 1
	fi

	(
		/bin/ls ../rpn_modules/lib*.so | sed 's:.*/lib\(.*\)\.so$:import \1:'
		echo 'catalog'
	) |  "$RPN" -ns | _hl --rpn.catalog | less -RXF
}

# catalog_all }}}
# catalog {{{
catalog()
{
	if [ "$1" = '' ]; then
		usage_catalog
		exit 1
	fi

	module="$1"
	echo "import $module catalog" | "$RPN" -ns | _hl --rpn.catalog | less -RXF
}
# catalog }}}
# list_modules {{{
list_modules()
{
	if [ "$1" != '' ]; then
		usage_list_modules
		exit 1
	fi

#	/bin/ls "$RPN_LIBPATH"/*.so | sed 's/.*lib\(.*\)\.so/\1/'
	rpn -sn <<- EOF | _hl --rpn.catalog
		`/bin/ls "$RPN_LIBPATH"/*.so | sed 's/.*lib\(.*\)\.so/import \1/'`
		modules
	EOF
}
# list_modules }}}
# search_op {{{

search_op()
{
	if [ "$1" = '' -o "$2" != '' ]; then
		usage_search_op
		exit 1
	fi
	op="$1"

	(
		/bin/ls ../rpn_modules/lib*.so | sed 's:.*/lib\(.*\)\.so$:import \1:'
		echo 'catalog'
	) |  "$RPN" -ns | sed -n "/\[$op\]/,/^[ 	]*$/p" |_hl --rpn.catalog | less -RXF
}

# search_op }}}
# MAIN PROGRAM {{{

PROGNAME="$(basename "$0")"
RPN='rpn'

if [ "$1" = '' ]; then
	usage
	exit 1
fi
module="$1"

flag_catalog_all=''
flag_catalog=''
flag_list_modules=''
flag_search_op=''

while getopts 'hcCMNs' opt
do
	case "$opt" in
		C)		flag_catalog_all='true'
				;;

		c)		flag_catalog='true'
				;;

		M)		flag_list_modules='true'
				;;

		s)		flag_search_op='true'
				;;

		N)		no_color='true'
				;;

		h|*)		usage
				exit 1
				;;
	esac
done
shift $(($OPTIND - 1))

if [ "$flag_catalog_all" = 'true' ]; then
	catalog_all "$@"
elif [ "$flag_catalog" = 'true' ]; then
	catalog "$@"
elif [ "$flag_list_modules" = 'true' ]; then
	list_modules "$@"
elif [ "$flag_search_op" = 'true' ]; then
	search_op "$@"
else
	usage
	exit 1
fi


# MAIN PROGRAM }}}
